name: CI con PostgreSQL y Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: outfitlab
          POSTGRES_USER: outfitlab
          POSTGRES_PASSWORD: outfitlab123
        ports:
          - 5433:5432
        # ğŸ‘‡ Espera a que la base estÃ© lista antes de ejecutar Maven
        options: >-
          --health-cmd="pg_isready -U outfitlab -d outfitlab"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout del cÃ³digo
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Esperar a que PostgreSQL estÃ© lista
        run: |
          echo "Esperando a que PostgreSQL estÃ© lista..."
          for i in {1..15}; do
            nc -z localhost 5433 && echo "Base de datos lista!" && break
            echo "Esperando ($i/15)..."
            sleep 5
          done

      - name: Compilar y ejecutar tests
        run: mvn clean test -Dspring.profiles.active=test
        env:
          SPRING_PROFILES_ACTIVE: test


#name: ci_outfitlab
#run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
#on:
#  pull_request:
#    branches: ["**"]
#  push:
#    branches: ["**"]
#jobs:
#  Run-Test:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "ğŸ‰ Esta tarea (job) fue lanzado automaticamente por el evento ${{ github.event_name }}"
#      - run: echo "ğŸ§ Esta tarea esta corriendo en un servidor ${{ runner.os }} por GitHub!"
#      - run: echo "ğŸ” El nombre de la rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
#      - name: Descargando el codigo
#        uses: actions/checkout@v3
#      - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} ha sido clonado."
#      - run: echo "ğŸ–¥ï¸ El workflow esta listo para testear el codigo"
#      - name: Corriendo las pruebas
#        run: |
#          mvn clean test
#      - run: echo "ğŸ El estado de la tarea es ${{ job.status }}."